### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CokkocZateki** [ddavaham/pinger#1]
A small wishlist which i think most would agree would be great

1. Fleet pings X amount of time before fleet starts. (editable if possible)
2. Able to Edit/Delete upcoming fleets
3. Is a big wish list and may not fly- Fleet tracking?

Thank you for such a wonderful app <3

**Comment by ddavaham** [comment]
1. Planned
2. Planned
3. No. This is a ping system for fleet operations. It is not mean to be a fleet tracker.

The purpose of the application is to manage fleet notifications and make it possible to easily disburse them.  There will be a read and write API that can be hit from outside the application to make it easy to pull fleet notifications on to another website and, with a admin token, update access list so that alliance auth systems can easily keep it up to date since technically it will be a application.

**Comment by CokkocZateki** [comment]
Awesome stuff
