### ISSUE TITLE
Discord Ping lists wrong date

### ISSUE THREAD

**Issue by Wirespeed91** [ddavaham/pinger#8]
Both Cain's and Klaire's fleets posted on Pinger showed March 3rd when initially pinged on Discord. In pinger it shows different dates.

Cain's ping: https://i.imgur.com/dZ03ITO.png
Klaire's Ping: https://i.imgur.com/idcmZse.png

site shows: https://i.imgur.com/Xrx2cjv.png

**Comment by ddavaham** [comment]
So I am not getting notifications for these issues for some reason, but I noticed this and fixed it already. I think you are on Comms when I did it. Thank You for reporting it though!

Fixed in this commit https://github.com/ddavaham/pinger/commit/21d48a6f2cf2f88422725baa7abe8a6f9e510800#diff-f1c4e387856e078d528d4a313e884bccL97
